server:
  port: 8080

spring:
  application:
    name: gateway

services:
  session:
    url: http://localhost:8082
  attendee:
    url: http://localhost:8081
  cfp:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
